# Generated by Django 3.2 on 2023-02-19 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelD',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelE',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('model_d1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modele1', to='testapp.modeld')),
                ('model_d2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modele2', to='testapp.modeld')),
                ('model_d3', models.ManyToManyField(blank=True, related_name='modele3', to='testapp.ModelD')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelC',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('model_d', models.ManyToManyField(blank=True, to='testapp.ModelD')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelB',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('model_b', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.modelb')),
                ('model_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.modelc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelA',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('model_b', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.modelb')),
                ('model_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.modelc')),
                ('model_d', models.ManyToManyField(blank=True, to='testapp.ModelD')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
