# Generated by Django 3.2 on 2023-02-20 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelB',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('model_b', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.modelb')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelC',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelD',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelE',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('model_b', models.ManyToManyField(blank=True, to='testapp.ModelB')),
                ('model_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.modelc')),
                ('model_d', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.modeld')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='modelc',
            name='model_d',
            field=models.ManyToManyField(blank=True, to='testapp.ModelD'),
        ),
        migrations.AddField(
            model_name='modelb',
            name='model_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.modelc'),
        ),
        migrations.CreateModel(
            name='ModelA',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('model_b', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.modelb')),
                ('model_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.modelc')),
                ('model_d', models.ManyToManyField(blank=True, to='testapp.ModelD')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
