# Generated by Django 4.2 on 2026-01-14 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20230305_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelb',
            name='model_cc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_b_cc', to='testapp.modelc'),
        ),
    ]
